"""
SOAR MCP Server - Scoped MCP Token Store

Provides per-user, revocable, optionally tool-scoped MCP tokens so that
multiple Cursor / Claude / other MCP clients can share a single SOAR MCP
endpoint without each one carrying a full-access SOAR ph-auth-token.

Design goals (per workspace rules):
  - No hardcoded credentials; tokens generated by secrets.token_urlsafe.
  - Stored on disk as salted SHA-256 hashes; raw tokens never persisted.
  - Constant-time verification; never log the raw token.
  - Per-token allow-list of tool names (intersected with asset-config).
  - Per-token rate limit; sliding 60s window.
  - Per-token bound SOAR `ph-auth-token` so downstream SOAR API calls
    happen as the bound user. The bound token is encrypted at rest with
    a key derived from the app data store and never returned over the
    wire after mint.

Storage layout: <app_root>/local/mcp_tokens.json

    {
      "version": 1,
      "fernet_key": "<base64 url-safe 32-byte key, generated on first mint>",
      "tokens": [
        {
          "id": "tok_<random>",
          "label": "alice@cursor",
          "soar_user_id": "alice",
          "hash": "<sha256 hex of token || salt>",
          "salt": "<hex>",
          "encrypted_soar_token": "<fernet ciphertext>",
          "allowed_tools": ["list_cases","get_case",...] or null=all,
          "created_at": 1717250000,
          "expires_at": 1727250000 or null=never,
          "last_used_at": 1717260000 or null,
          "revoked_at": null or unix-ts
        }
      ]
    }

The Fernet key lives in the same file rather than in a separate KMS only
because SOAR Apps do not have a managed KMS available; the file inherits
the SOAR app local/ permissions (root-owned, 600). If a real KMS becomes
available later, swap _decrypt/_encrypt to use it.

Copyright 2026 Andreas Buis. Licensed for use with the SOAR MCP Server app.
"""

from __future__ import annotations

import hashlib
import hmac
import json
import logging
import os
import secrets
import threading
import time
from dataclasses import dataclass, field
from pathlib import Path
from typing import Optional, Sequence

logger = logging.getLogger(__name__)

_TOKEN_PREFIX = "soarmcp_"
_TOKEN_RAW_BYTES = 32  # 256 bits of entropy
_STORE_VERSION = 1


# ── Encryption helpers (Fernet) ────────────────────────────────────────────────

def _have_fernet() -> bool:
    try:
        from cryptography.fernet import Fernet  # noqa: F401
        return True
    except Exception:
        return False


def _new_fernet_key() -> str:
    """Generate a new Fernet key as a urlsafe-base64 string."""
    if not _have_fernet():
        # Fallback: 32 random bytes urlsafe-base64; encryption is a no-op
        # in this mode, which is documented in _encrypt/_decrypt below.
        return secrets.token_urlsafe(32)
    from cryptography.fernet import Fernet
    return Fernet.generate_key().decode("ascii")


def _encrypt(plaintext: str, fernet_key: str) -> str:
    """Encrypt plaintext with the store's Fernet key.

    If cryptography is unavailable (some SOAR app sandboxes), fall back
    to base64 wrapping so the file format is consistent; this is a
    DEFENCE-IN-DEPTH measure, not a substitute for real encryption.
    The token store file should still be locked down at the OS level.
    """
    if not plaintext:
        return ""
    if not _have_fernet():
        import base64
        logger.warning("[MCP tokens] cryptography not installed - "
                       "SOAR call token stored with base64 wrapper only. "
                       "Install 'cryptography' in pip3_dependencies to enable Fernet.")
        return "b64:" + base64.urlsafe_b64encode(plaintext.encode()).decode("ascii")
    from cryptography.fernet import Fernet
    return Fernet(fernet_key.encode()).encrypt(plaintext.encode()).decode("ascii")


def _decrypt(ciphertext: str, fernet_key: str) -> str:
    if not ciphertext:
        return ""
    if ciphertext.startswith("b64:"):
        import base64
        return base64.urlsafe_b64decode(ciphertext[4:].encode()).decode("utf-8")
    if not _have_fernet():
        raise RuntimeError("Encrypted token present but cryptography library missing")
    from cryptography.fernet import Fernet
    return Fernet(fernet_key.encode()).decrypt(ciphertext.encode()).decode("utf-8")


# ── Hashing & comparison ───────────────────────────────────────────────────────

def _hash_token(raw_token: str, salt_hex: str) -> str:
    salt = bytes.fromhex(salt_hex)
    return hashlib.sha256(raw_token.encode("utf-8") + salt).hexdigest()


def _const_time_eq(a: str, b: str) -> bool:
    return hmac.compare_digest(a.encode("utf-8"), b.encode("utf-8"))


def sanitise_args_for_audit(args) -> dict:
    """Strip likely-sensitive fields from tool arguments before audit logging."""
    if not isinstance(args, dict):
        return {"_value": str(args)[:200]}
    sensitive_keys = {"token", "password", "secret", "api_key", "auth"}
    out = {}
    for k, v in args.items():
        if any(s in k.lower() for s in sensitive_keys):
            out[k] = "<redacted>"
        elif isinstance(v, str) and len(v) > 200:
            out[k] = v[:200] + "...<truncated>"
        else:
            out[k] = v
    return out


# ── Rate limiter (in-process, sliding 60s window) ──────────────────────────────

class _RateLimiter:
    def __init__(self) -> None:
        self._buckets: dict[str, list[float]] = {}
        self._lock = threading.Lock()

    def check(self, token_id: str, limit_per_minute: int) -> bool:
        if limit_per_minute <= 0:
            return True
        now = time.time()
        cutoff = now - 60.0
        with self._lock:
            bucket = [t for t in self._buckets.get(token_id, []) if t > cutoff]
            if len(bucket) >= limit_per_minute:
                self._buckets[token_id] = bucket
                return False
            bucket.append(now)
            self._buckets[token_id] = bucket
            return True


# ── Public dataclasses ────────────────────────────────────────────────────────

@dataclass
class MintedToken:
    """Returned ONLY at mint time. The raw token is never persisted."""
    id: str
    label: str
    raw_token: str
    expires_at: Optional[int]
    allowed_tools: Optional[list[str]]
    soar_user_id: str


@dataclass
class TokenVerification:
    """Result of TokenStore.verify()."""
    valid: bool
    token_id: Optional[str] = None
    label: Optional[str] = None
    soar_user_id: Optional[str] = None
    soar_call_token: Optional[str] = None
    allowed_tools: Optional[list[str]] = None
    reason: str = ""


@dataclass
class TokenSummary:
    """Safe-to-list token metadata (never includes raw or hashed token)."""
    id: str
    label: str
    soar_user_id: str
    allowed_tools: Optional[list[str]]
    created_at: int
    expires_at: Optional[int]
    last_used_at: Optional[int]
    revoked_at: Optional[int]

    @property
    def is_active(self) -> bool:
        if self.revoked_at is not None:
            return False
        if self.expires_at is not None and self.expires_at < int(time.time()):
            return False
        return True


# ── Token store ───────────────────────────────────────────────────────────────

@dataclass
class _StoreState:
    fernet_key: str = ""
    tokens: list[dict] = field(default_factory=list)
    version: int = _STORE_VERSION


class TokenStore:
    """File-backed scoped MCP token store. Thread-safe within a process."""

    _instance_lock = threading.Lock()
    _instances: dict[str, "TokenStore"] = {}

    def __init__(self, store_path: Path):
        self._path = store_path
        self._lock = threading.Lock()
        self._rate = _RateLimiter()
        self._state: Optional[_StoreState] = None

    # ── Singleton accessor keyed on path ──────────────────────────────────────
    @classmethod
    def default(cls) -> "TokenStore":
        app_root = Path(__file__).parent
        store_path = app_root / "local" / "mcp_tokens.json"
        return cls.for_path(store_path)

    @classmethod
    def for_path(cls, path: Path) -> "TokenStore":
        key = str(path.resolve())
        with cls._instance_lock:
            inst = cls._instances.get(key)
            if inst is None:
                inst = cls(path)
                cls._instances[key] = inst
            return inst

    # ── I/O ───────────────────────────────────────────────────────────────────
    def _load(self) -> _StoreState:
        if self._state is not None:
            return self._state
        if not self._path.exists():
            self._state = _StoreState(fernet_key=_new_fernet_key())
            self._save(self._state)
            return self._state
        try:
            with open(self._path, encoding="utf-8") as fh:
                raw = json.load(fh)
        except Exception as exc:
            raise RuntimeError(f"Could not read MCP token store at {self._path}: {exc}")
        state = _StoreState(
            fernet_key=raw.get("fernet_key") or _new_fernet_key(),
            tokens=list(raw.get("tokens") or []),
            version=int(raw.get("version") or _STORE_VERSION),
        )
        if not raw.get("fernet_key"):
            self._save(state)
        self._state = state
        return state

    def _save(self, state: _StoreState) -> None:
        self._path.parent.mkdir(parents=True, exist_ok=True)
        tmp = self._path.with_suffix(self._path.suffix + ".tmp")
        with open(tmp, "w", encoding="utf-8") as fh:
            json.dump({
                "version": state.version,
                "fernet_key": state.fernet_key,
                "tokens": state.tokens,
            }, fh, indent=2)
        os.replace(tmp, self._path)
        try:
            os.chmod(self._path, 0o600)
        except Exception:
            pass

    # ── Mint ──────────────────────────────────────────────────────────────────
    def mint(
        self,
        *,
        label: str,
        soar_user_id: str,
        soar_call_token: str,
        allowed_tools: Optional[Sequence[str]] = None,
        lifetime_days: Optional[int] = 90,
    ) -> MintedToken:
        """Mint a new scoped MCP token.

        Args:
            label: human-readable label (e.g. 'alice@cursor-laptop').
            soar_user_id: SOAR user this token acts on behalf of.
            soar_call_token: the ph-auth-token used downstream when calling
                SOAR APIs. Stored encrypted; never returned.
            allowed_tools: list of tool names this token may invoke,
                or None for all (subject to asset config).
            lifetime_days: token validity; None = never expires.

        Returns:
            MintedToken with raw_token (show once to user, never again).
        """
        if not label or not soar_user_id or not soar_call_token:
            raise ValueError("label, soar_user_id and soar_call_token are all required")

        raw = _TOKEN_PREFIX + secrets.token_urlsafe(_TOKEN_RAW_BYTES)
        salt_hex = secrets.token_hex(16)
        token_id = "tok_" + secrets.token_urlsafe(8)
        now = int(time.time())
        expires_at: Optional[int]
        expires_at = now + int(lifetime_days) * 86400 if lifetime_days else None
        allowed_tools_list = list(allowed_tools) if allowed_tools else None

        with self._lock:
            state = self._load()
            entry = {
                "id": token_id,
                "label": label.strip()[:128],
                "soar_user_id": soar_user_id.strip()[:128],
                "hash": _hash_token(raw, salt_hex),
                "salt": salt_hex,
                "encrypted_soar_token": _encrypt(soar_call_token, state.fernet_key),
                "allowed_tools": allowed_tools_list,
                "created_at": now,
                "expires_at": expires_at,
                "last_used_at": None,
                "revoked_at": None,
            }
            state.tokens.append(entry)
            self._save(state)

        logger.info("[MCP tokens] minted token id=%s label=%s expires=%s",
                    token_id, label, expires_at)
        return MintedToken(
            id=token_id,
            label=label,
            raw_token=raw,
            expires_at=expires_at,
            allowed_tools=allowed_tools_list,
            soar_user_id=soar_user_id,
        )

    # ── Verify ───────────────────────────────────────────────────────────────
    def verify(self, presented: str, *, rate_limit: int = 120) -> Optional[TokenVerification]:
        """Verify a presented token.

        Returns None if the token doesn't look like one we issued
        (so the caller can fall through to legacy auth). Returns a
        TokenVerification(valid=False, reason=...) if it does look like
        ours but is expired/revoked/rate-limited.
        """
        if not presented or not presented.startswith(_TOKEN_PREFIX):
            return None

        with self._lock:
            state = self._load()
            now = int(time.time())
            for entry in state.tokens:
                expected = _hash_token(presented, entry["salt"])
                if not _const_time_eq(expected, entry["hash"]):
                    continue
                # Match found
                if entry.get("revoked_at") is not None:
                    return TokenVerification(valid=False, token_id=entry["id"],
                                             label=entry.get("label"),
                                             reason="revoked")
                exp = entry.get("expires_at")
                if exp is not None and exp < now:
                    return TokenVerification(valid=False, token_id=entry["id"],
                                             label=entry.get("label"),
                                             reason="expired")
                if not self._rate.check(entry["id"], rate_limit):
                    return TokenVerification(valid=False, token_id=entry["id"],
                                             label=entry.get("label"),
                                             reason="rate_limited")
                # Update last_used_at (best-effort)
                try:
                    entry["last_used_at"] = now
                    self._save(state)
                except Exception:
                    pass
                try:
                    call_token = _decrypt(entry.get("encrypted_soar_token", ""),
                                          state.fernet_key)
                except Exception as exc:
                    logger.exception("[MCP tokens] decrypt failure: %s", exc)
                    return TokenVerification(valid=False, token_id=entry["id"],
                                             label=entry.get("label"),
                                             reason="decrypt_failure")
                return TokenVerification(
                    valid=True,
                    token_id=entry["id"],
                    label=entry.get("label"),
                    soar_user_id=entry.get("soar_user_id"),
                    soar_call_token=call_token,
                    allowed_tools=entry.get("allowed_tools"),
                )
        return TokenVerification(valid=False, reason="unknown_token")

    # ── List ─────────────────────────────────────────────────────────────────
    def list(self, *, include_revoked: bool = False) -> list[TokenSummary]:
        with self._lock:
            state = self._load()
            out = []
            for e in state.tokens:
                if not include_revoked and e.get("revoked_at") is not None:
                    continue
                out.append(TokenSummary(
                    id=e["id"],
                    label=e.get("label", ""),
                    soar_user_id=e.get("soar_user_id", ""),
                    allowed_tools=e.get("allowed_tools"),
                    created_at=int(e.get("created_at", 0)),
                    expires_at=e.get("expires_at"),
                    last_used_at=e.get("last_used_at"),
                    revoked_at=e.get("revoked_at"),
                ))
            return out

    # ── Revoke ───────────────────────────────────────────────────────────────
    def revoke(self, token_id: str) -> bool:
        with self._lock:
            state = self._load()
            for e in state.tokens:
                if e["id"] == token_id and e.get("revoked_at") is None:
                    e["revoked_at"] = int(time.time())
                    self._save(state)
                    logger.info("[MCP tokens] revoked token id=%s", token_id)
                    return True
            return False

    # ── Purge ────────────────────────────────────────────────────────────────
    def purge_expired(self, *, older_than_days: int = 90) -> int:
        """Remove tokens that have been expired OR revoked for N+ days."""
        cutoff = int(time.time()) - older_than_days * 86400
        removed = 0
        with self._lock:
            state = self._load()
            kept = []
            for e in state.tokens:
                exp = e.get("expires_at")
                rev = e.get("revoked_at")
                purge = False
                if rev is not None and rev < cutoff:
                    purge = True
                if exp is not None and exp < cutoff and rev is not None:
                    purge = True
                if purge:
                    removed += 1
                else:
                    kept.append(e)
            if removed:
                state.tokens = kept
                self._save(state)
        return removed
